name: fruitfairy
description: A new Flutter project.

# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  provider: ^4.3.3
  http: ^0.12.2
  uuid: ^2.2.2
  flutter_secure_storage: ^3.3.5
  flutter_circular_text: ^0.3.0
  flutter_typeahead: ^2.0.0
  font_awesome_flutter: ^8.11.0
  phone_number: ^0.8.1+1
  modal_progress_hud: ^0.1.3
  scroll_to_index: ^1.0.6
  rflutter_alert: ^1.1.0
  strings: ^0.1.4
  cached_network_image: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
